### ISSUE TITLE
"Mage registry key "_singleton/dpd/observer" already exists"

### ISSUE THREAD

**Issue by pydubreucq** [DPDBeNeLux/magento-DPD_Shipping#29]
Hi,
I'm trying to migrate one Magento with DPDShipping extension, but I have this error :
```
a:5:{i:0;s:58:"Mage registry key "_singleton/dpd/observer" already exists";i:1;s:3132:"#0 /home/site2079/www/app/Mage.php(222): Mage::throwException('Mage registry k...')
#1 /home/site2079/www/app/Mage.php(476): Mage::register('_singleton/dpd/...', false)
#2 /home/site2079/www/includes/src/__default.php(21727): Mage::getSingleton('dpd/observer')
#3 /home/site2079/www/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('core_block_abst...', Array)
#4 /home/site2079/www/includes/src/__default.php(4034): Mage::dispatchEvent('core_block_abst...', Array)
#5 /home/site2079/www/includes/src/__default.php(3720): Mage_Core_Block_Abstract->toHtml()
#6 /home/site2079/www/includes/src/__default.php(3660): Mage_Core_Block_Abstract->_getChildHtml('optional_zip_co...', true)
#7 /home/site2079/www/app/design/frontend/default/yatoo/template/page/html/head.phtml(26): Mage_Core_Block_Abstract->getChildHtml()
#8 /home/site2079/www/includes/src/__default.php(4715): include('/home/site2079/...')
#9 /home/site2079/www/includes/src/__default.php(4746): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#10 /home/site2079/www/includes/src/__default.php(4760): Mage_Core_Block_Template->renderView()
#11 /home/site2079/www/includes/src/__default.php(4007): Mage_Core_Block_Template->_toHtml()
#12 /home/site2079/www/includes/src/__default.php(3720): Mage_Core_Block_Abstract->toHtml()
#13 /home/site2079/www/includes/src/__default.php(3664): Mage_Core_Block_Abstract->_getChildHtml('head', true)
#14 /home/site2079/www/app/design/frontend/default/yatoo/template/page/1column.phtml(9): Mage_Core_Block_Abstract->getChildHtml('head')
#15 /home/site2079/www/includes/src/__default.php(4715): include('/home/site2079/...')
#16 /home/site2079/www/includes/src/__default.php(4746): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#17 /home/site2079/www/includes/src/__default.php(4760): Mage_Core_Block_Template->renderView()
#18 /home/site2079/www/includes/src/__default.php(4007): Mage_Core_Block_Template->_toHtml()
#19 /home/site2079/www/includes/src/__default.php(28097): Mage_Core_Block_Abstract->toHtml()
#20 /home/site2079/www/includes/src/__default.php(391): Mage_Core_Model_Layout->getOutput()
#21 /home/site2079/www/includes/src/__default.php(12639): Mage_Core_Controller_Varien_Action->renderLayout()
#22 /home/site2079/www/includes/src/__default.php(12554): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'home')
#23 /home/site2079/www/app/code/core/Mage/Cms/controllers/IndexController.php(45): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'home')
#24 /home/site2079/www/includes/src/__default.php(420): Mage_Cms_IndexController->indexAction()
#25 /home/site2079/www/includes/src/__default.php(18610): Mage_Core_Controller_Varien_Action->dispatch('index')
#26 /home/site2079/www/includes/src/__default.php(18161): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /home/site2079/www/includes/src/__default.php(20765): Mage_Core_Controller_Varien_Front->dispatch()
#28 /home/site2079/www/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#29 /home/site2079/www/index.php(87): Mage::run('', 'store')
#30 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"fr";}
```

My last server run with php5.3 and the new one with php5.4

Do you have an idea ?

Thanks a lot
Best Regards,
Pierre-Yves

**Comment by mvgucht** [comment]
Hey pydubreucq,

first time that I've seen this error, but [stackexchange] (http://magento.stackexchange.com/questions/59406/error-mage-registry-key-singleton-rkt-jscssforsb-observer-already-exists) to the rescue.

It talks about an other module but the logic is the same. I would try clearing the cache (fully) and see if that fixes the problem.
